Objetivo 1
vlljuan99/gasolinapp pull request #11
Opened 2021-09-27 09:34 UTC by vlljuan99

Añade issues, milestones y el nuevo archivo docs, entre otros cambios menores. Lo necesario para obtener el objetivo 1 (sobre el papel).

2021-09-28 12:07 UTC, JJ requested changes
Por favor, formula los milestones como productos mínimamente viables. Si no sabes qué producto vas a construir y en qué secuencia,¿cómo puedes ponerte a programar?

2021-09-30 07:51 UTC, vlljuan99 commented
> Por favor, formula los milestones como productos mínimamente viables. Si no sabes qué producto vas a construir y en qué secuencia,¿cómo puedes ponerte a programar?

He formulado los milestones como 4 módulos, 3 de ellos independientes entre sí (M1, M2 y M3) y un último módulo (M4) que los aúna todos para conseguir la funcionalidad final de la app, con eso bastaría para empezar a programar, ¿verdad?

2021-09-30 07:52 UTC, vlljuan99 commented
He añadido también un user journey y un ejemplo del cálculo de la gasolinera más óptima [aquí](https://github.com/vlljuan99/gasolinapp/blob/Objetivo-1/docs/user_journey.md). Creo que es muy útil para saber cómo quiero que funcione la app de cara al usuario y para explicar qué entiendo por escoger la gasolinera óptima.

2021-09-30 08:07 UTC, vlljuan99 commented
Necesito darle una vuelta a los [issues](https://github.com/vlljuan99/gasolinapp/issues). Creo que, al contrario que los (milestones)[https://github.com/vlljuan99/gasolinapp/milestones], no explican bien los aspectos de la aplicación, pero no sé cómo enfocarlos.

Sin embargo creo que con el [user journey](https://github.com/vlljuan99/gasolinapp/blob/Objetivo-1/docs/user_journey.md) debería bastar para explicar cómo se usa la app y cómo quiero que funcione. ¿Cómo enfoco desde ahí las HU?

2021-09-30 15:25 UTC, JJ commented
> Necesito darle una vuelta a los [issues](https://github.com/vlljuan99/gasolinapp/issues). Creo que, al contrario que los [milestones](https://github.com/vlljuan99/gasolinapp/milestones), no explican bien los aspectos de la aplicación, pero no sé cómo enfocarlos.
> 
> Sin embargo creo que con el [user journey](https://github.com/vlljuan99/gasolinapp/blob/Objetivo-1/docs/user_journey.md) debería bastar para explicar cómo se usa la app y cómo quiero que funcione. ¿Cómo enfoco desde ahí las HU?

Tratando de extraer de ese "user journey" diferentes requisitos y contextos que se expondrán en una HU.

2021-09-30 15:26 UTC, JJ approved these changes
Te vas a dar cuenta de que, como hemos dicho en clase, necesitas el módulo inicial que incluya sólo el diseño. Pero por lo demás, creo que has alcanzado el objetivo de forma basante razonable.

2021-10-01 11:42 UTC, merged

2021-10-02 09:37 UTC, JJ commented
El siguiente objetivo se le asigna a @paula1999

2021-10-04 09:56 UTC, vlljuan99 commented
> El siguiente objetivo se le asigna a @paula1999

He añadido el (milestone 0)[https://github.com/vlljuan99/gasolinapp/milestone/5] para que el comienzo del desarrollo del proyecto sea más sencillo y guiado para @paula1999, creo que es suficientemente explicativo.

Son dos clases muy básicas que me van a servir como base para el resto de módulos, la clase 'Gasolinera' y la clase 'Vehículo'.

2021-10-04 15:40 UTC, JJ commented
> > El siguiente objetivo se le asigna a @paula1999
> 
> He añadido el [milestone 0](https://github.com/vlljuan99/gasolinapp/milestone/5) para que el comienzo del desarrollo del proyecto sea más sencillo y guiado para @paula1999, creo que es suficientemente explicativo.
> 
> Son dos clases muy básicas que me van a servir como base para el resto de módulos, la clase 'Gasolinera' y la clase 'Vehículo'.

Por favor, recordad el diseño dirigido por dominio que os expliqué en clase. Evidentemente, eso tendrá que estar. Pero no serán nunca entidades.