Añade task_runner.md
vlljuan99/gasolinapp pull request #21
Opened 2021-11-24 10:50 UTC by vlljuan99

Explico brevemente por qué he elegido Rake como gestor de tareas

2021-11-24 15:16 UTC, vlljuan99 commented
listo para revisión, @JJ.

2021-11-28 11:09 UTC, JJ requested changes
Un par de vueltas y alcanzas el objetivo.

2021-11-28 11:09 UTC, JJ commented on README.md
> +sudo snap install ruby --classic
No se instalan nunca los lenguajes con permiso de superusuario, ni ninguna herramienta de desarrollo. Dicho *repetidamente* en clase.

2021-11-28 11:09 UTC, JJ commented on Rakefile
> +task :test do
Estas tareas no están añadidas con un commit que se refiera a un issue. Nunca se puede avanzar en código (ni en infraestructura-como-código) sin un issue.

2021-11-28 11:09 UTC, JJ commented on docs/task_runner.md
> +### ¿Por qué usaremos Rake?
No hay ningún examen de las herramientas disponibles, ni los requisitos para elegirlas.

2021-11-29 10:01 UTC, vlljuan99 commented on README.md
> +sudo snap install ruby --classic
ok, culpa mía, corregido 👍🏻

2021-11-29 10:02 UTC, vlljuan99 commented on Rakefile
> +task :test do
Fallo mío por hacerlo rápido sin pensar en los pasos necesarios, también corregido 👍🏻

2021-11-29 10:02 UTC, vlljuan99 commented on docs/task_runner.md
> +### ¿Por qué usaremos Rake?
No entiendo esta revisión, no sé a qué se refiere. Le pregunto por Telegram.

2021-11-29 11:16 UTC, vlljuan99 commented
He corregido los cambios que me pedías. Diría que está listo para revisión de nuevo, @JJ.

2021-11-29 12:03 UTC, JJ requested changes
Mira la lista de comprobación del objetivo, y los errores frecuentes en las sesiones en las que se ha tratado este objetivo.

2021-11-29 12:03 UTC, JJ commented on README.md
> +snap install ruby --classic
Aunque le hayas quitado el sudo, sigues sin instalar correctamente ruby. Se tiene que usar una herramienta de gestión de versiones de la que hemos hablado. Nunca se debe instalar "el que esté en los repos". Por favor, en vez de quedaros con la letra de lo que os comento y hacerlo a ciegas tratad de entender por qué se pide una cosa. Si no estáis dando palos de ciego.

2021-11-29 12:03 UTC, JJ commented on Rakefile
> +    exec "sudo gem install bundler"
¿Ves lo que pasa cuando no entiendes por qué se piden las cosas?

2021-11-29 12:03 UTC, JJ commented on docs/task_runner.md
> +Podemos encontrar distintos Task Runner para Ruby, entre ellos:
¿Podemos encontrar si buscamos qué?

2021-11-29 12:03 UTC, JJ commented on docs/task_runner.md
> +Rake es una herramienta que podemos utilizar con proyectos Ruby, básicamente es un manejador de tareas muy popular para este lenguaje.
¿La popularidad es el criterio técnico que has usado para elegir uno u otro? ¿Has puesto el resto porque te he pedido que lo pongas, para quedarte con el que ya tenías de antemano? ¿Qué crees que consigo yo con que me escribas dos o tres task runners más? ¿Qué objetivo de aprendizaje has alcanzado con eso?

2021-12-02 17:03 UTC, vlljuan99 commented on README.md
> +snap install ruby --classic
No usé un manejador de versiones como RVM, que es lo útil y correcto. Lo he corregido y actualmente estoy usando la versión 3.0.0, (instalada obviamente con RVM), no sé si debería informar de ello en el README.

2021-12-02 17:38 UTC, vlljuan99 commented on docs/task_runner.md
> +Rake es una herramienta que podemos utilizar con proyectos Ruby, básicamente es un manejador de tareas muy popular para este lenguaje.
* Debería haberlo aclarado, ahora lo corrijo y pongo los criterios por los que creo que es la mejor opción.
* No, puse 2 más a modo de ejemplo y aún así Rake me sigue pareciendo la mejor opción de entre las estudiadas, ya que tiene más documentación y soporte, porque es más popular que el resto. Además, creo que el hecho de que esté escrito en Ruby y que sea make-like como el make de UNIX hace que esté muy cómodo con la elección.
* Nada, culpa mía por hacerlo rápido y mal.
* Ninguno, disculpa.

2021-12-02 17:40 UTC, vlljuan99 commented on Rakefile
> +    exec "sudo gem install bundler"
Pedía usar Rakefile sin instalar Rake, disculpa, corregido.

2021-12-02 18:06 UTC, vlljuan99 commented
Diría que está listo para revisión de nuevo, @JJ.

2021-12-05 19:57 UTC, JJ commented on Rakefile
> +    exec "sudo gem install bundler"
El problema es el `sudo`... Que lo usaste antes en `sudo snap` Vamos a ver qué has corregido...

2021-12-05 20:03 UTC, JJ approved these changes
A ver no te voy a pedir que justifiques Rake, porque todo el mundo sabe que Rake *es el gestor de tareas*. Pero de ahora en adelante tienes que justificar las elecciones de la forma que lo hemos explicado en clase.

2021-12-05 20:03 UTC, JJ commented on docs/task_runner.md
> +### Características de Rake para que sea nuestro task runner elegido:
Estás justificando por qué has elegido Rake, no poniendo unos criterios por lo que lo has elegido. Son justificaciones a posteriori, no criterios a priori. ¿Tu proyecto necesita que las tareas se comuniquen entre si? ¿Necesitan requisitos previos? Puede que sean cosas que no tienen los otros, pero da igual, porque no los vas a usar.

2021-12-05 20:03 UTC, JJ commented on docs/task_runner.md
> +
Para empezar, tendrías que decir qué características tiene que tener un gestor de tareas para ser elegido.
Da igual a estas alturas, pero por favor sigue esos criterios en el resto de los objetivos, donde siempre hay que elegir algo.

2021-12-09 16:18 UTC, merged